app:
  port: 31339
  host: 127.0.0.1

logDebug:
  postfix: :app-prod
  enableInfo: false
  enableDev: false
  enableError: false
  enableServerStream: false

log:
  label: :app-prod
  enableConsole: false
  pathError: null
  pathLog: null
